cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'awscli'
brew 'bash-completion'
brew 'chromedriver'
brew 'gawk'
brew 'git'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'mysql'
brew 'node'
brew 'opam'
brew 'openssl'
brew 'phantomjs'
brew 'pyenv'
brew 'rbenv'
brew 'ruby'
brew 'ruby-build'
brew 'tmux'
brew 'wget'

cask 'iterm2'
cask 'java'
cask 'atom'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'sequel-pro'
cask 'spotify'
cask 'virtualbox'
cask 'visual-studio-code'
