cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'dart-lang/dart'
tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'dart', args: ['with-content-shell', 'with-dartium']
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'maven2'
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'pass'
brew 'phantomjs'
brew 'rbenv'
brew 'ruby-build'
brew 'wget'

cask 'atom'
cask 'firefox'
cask 'flash-player-debugger'
cask 'flash-player'
cask 'ghc'
cask 'google-chrome'
cask 'hipchat'
cask 'intellij-idea'
cask 'sequel-pro'
cask 'spotify'
cask 'virtualbox'
