#!/usr/bin/env bash
#
# Run all dotfile installers.

set -e

cd "$(dirname $0)"/..

echo "› brew bundle"
brew bundle --no-upgrade || true

find . -name install.sh | while read installer ; do
  echo "› running installer in $(dirname ${installer})"
  sh -c "${installer}" ;
done
